apiVersion: v1
kind: Service
metadata:
  name: formulagraphql
  labels:
    app: formulagraphql
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: formulagraphql
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: webapp