apiVersion: v1
kind: Service
metadata:
  name: formulagraphql
  labels:
    run: formulagraphql
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    run: formulagraphql
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    run: webapp
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    run: webapp