apiVersion: v1
kind: Service
metadata:
  name: formulagraphql
  labels:
    app: formulagraphql
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: formulagraphql
---
apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    app: web
  annotations:
    dev.okteto.com/auto-ingress: "web"
spec:
  ports:
  - port: 8081
    protocol: TCP
  selector:
    app: web