// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Circuit struct {
	ID          *string   `json:"id"`
	URL         *string   `json:"url"`
	CircuitName *string   `json:"circuitName"`
	Location    *Location `json:"location"`
}

type CircuitsReport struct {
	Season   *string    `json:"season"`
	Circuits []*Circuit `json:"circuits"`
}

type Constructor struct {
	ID          *string `json:"id"`
	Name        *string `json:"name"`
	URL         *string `json:"url"`
	Nationality *string `json:"nationality"`
}

type ConstructorStandingsReport struct {
	Season *string         `json:"season"`
	Round  *string         `json:"round"`
	Teams  []*TeamStanding `json:"teams"`
}

type Driver struct {
	ID          *string `json:"id"`
	Number      *string `json:"number"`
	Code        *string `json:"code"`
	URL         *string `json:"url"`
	GivenName   *string `json:"givenName"`
	FamilyName  *string `json:"familyName"`
	DateOfBirth *string `json:"dateOfBirth"`
	Nationality *string `json:"nationality"`
}

type DriverStanding struct {
	Position *string `json:"position"`
	Points   *string `json:"points"`
	Wins     *string `json:"wins"`
	Driver   *Driver `json:"Driver"`
}

type DriverStandingsReport struct {
	Season  *string           `json:"season"`
	Round   *string           `json:"round"`
	Drivers []*DriverStanding `json:"drivers"`
}

type Lap struct {
	Round    *string   `json:"round"`
	Lap      *string   `json:"lap"`
	URL      *string   `json:"url"`
	RaceName *string   `json:"raceName"`
	Date     *string   `json:"date"`
	Time     *string   `json:"time"`
	Circuit  *Circuit  `json:"circuit"`
	Timings  []*Timing `json:"timings"`
}

type LapTimesFilter struct {
	Year  *string `json:"year"`
	Round *string `json:"round"`
	Lap   *string `json:"lap"`
}

type LapTimesReport struct {
	Season *string `json:"season"`
	Laps   []*Lap  `json:"laps"`
}

type Location struct {
	Lat      *string `json:"lat"`
	Long     *string `json:"long"`
	Locality *string `json:"locality"`
	Country  *string `json:"country"`
}

type Race struct {
	Round    *string  `json:"round"`
	URL      *string  `json:"url"`
	RaceName *string  `json:"raceName"`
	Date     *string  `json:"date"`
	Time     *string  `json:"time"`
	Circuit  *Circuit `json:"circuit"`
}

type ScheduleReport struct {
	Season *string `json:"season"`
	Races  []*Race `json:"races"`
}

type StandingsFilter struct {
	Year  *string `json:"year"`
	Round *string `json:"round"`
	Top   *int    `json:"top"`
}

type TeamStanding struct {
	Position *string      `json:"position"`
	Points   *string      `json:"points"`
	Wins     *string      `json:"wins"`
	Team     *Constructor `json:"team"`
}

type Timing struct {
	DriverID *string `json:"driverID"`
	Position *string `json:"position"`
	Time     *string `json:"time"`
}
