on:
  pull_request:
    types: [opened, edited, reopened]

jobs: 
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test backend
        run: cd formulagraphql && go test -v ./...

      - name: Test frontend
        run: cd webapp && go test -v ./...

  preview-okteto:
    needs: [ build-publish ]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Trigger the pipeline"
      uses: okteto/deploy-preview@latest
      with:
        name: ${{ github.event.pull_request.head.ref }}-trelore
        timeout: 8m

  e2e-test:
    needs: [ deploy-okteto ]
    defaults:
      run:
        working-directory: e2e-tests
    env:
      BASE_URL: https://${{ github.event.pull_request.head.ref }}-trelore.cloud.okteto.net
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test

  destroy-okteto-preview:
    needs: [ e2e-test ]
    runs-on: ubuntu-latest
    steps:
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Destroy the preview"
      uses: okteto/destroy-preview@latest
      with:
        name: ${{ github.event.pull_request.head.ref }}-trelore
