name: push

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v ./...

  build-publish:
    runs-on: ubuntu-latest
    needs: [ test ]
    steps:
      # checkout code
      - uses: actions/checkout@v2
      # build model, build binary
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # docker login and push
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (formulagraphql)
        id: docker_build_formula1
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/trelore/formulagraphql:latest
          file: graphql.Dockerfile
      - name: Build and push (webapp)
        id: docker_build_webapp
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/trelore/webapp:latest
          file: webapp.Dockerfile