name: push

on:
  push:
    branches: [ main ]

env:
  BASE_URL: https://webapp-trelore.cloud.okteto.net

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Test backend
        run: cd formulagraphql && go test -v ./...

      - name: Test frontend
        run: cd webapp && go test -v ./...

  build-publish:
    runs-on: ubuntu-latest
    needs: [ unit-test ]
    steps:
      # checkout code
      - uses: actions/checkout@v2
      # build model, build binary
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      # docker login and push
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push (formulagraphql)
        id: docker_build_formula1
        uses: docker/build-push-action@v2
        with:
          context: ./formulagraphql
          push: true
          tags: ghcr.io/trelore/formulagraphql:latest
          file: formulagraphql/Dockerfile
      - name: Build and push (webapp)
        id: docker_build_webapp
        uses: docker/build-push-action@v2
        with:
          context: ./webapp
          push: true
          tags: ghcr.io/trelore/webapp:latest
          file: webapp/Dockerfile

  deploy-okteto:
    needs: [ build-publish ]
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master

    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: trelore

    - name: "Trigger the pipeline"
      uses: okteto/pipeline@latest
      with:
        name: main
        timeout: 8m

  e2e-test:
    needs: [ deploy-okteto ]
    defaults:
      run:
        working-directory: e2e-tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  destroy-okteto:
    needs: [ e2e-test ]
    runs-on: ubuntu-latest
    steps:
    - uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}

    - name: "Activate Namespace"
      uses: okteto/namespace@latest
      with:
        name: trelore

    - name: "Destroy the pipeline"
      uses: okteto/destroy-pipeline@latest
      with:
        name: main